import React, { FC } from 'react';
import { MDBDataTable } from 'mdbreact';

export const DatatablePage: FC = () => {
  type tableData = {
    treatmentNumber: string;
    treatmentInformation: string;
    date: string;
    workerEmail: Date;
    carNumber: string;
  };
  const data = {
    columns: [
      {
        label: 'Treatment Number',
        field: 'treatmentNumber',
        sort: 'asc',
        width: 150,
      },
      {
        label: 'Treatment Information',
        field: 'treatmentInformation',
        sort: 'asc',
        width: 270,
      },
      {
        label: 'Date',
        field: 'date',
        sort: 'asc',
        width: 200,
      },
      {
        label: 'Worker email',
        field: 'workerEmail',
        sort: 'asc',
        width: 100,
      },
      {
        label: 'Car Number',
        field: 'carNumber',
        sort: 'asc',
        width: 150,
      },
    ],
    rows: [
      {
        treatmentNumber: 1,
        treatmentInformation: 'Vachel',
        workerEmail: 'Coviello',
        carNumber: 'vcoviello0@wordpress.org',
        date: 'Male',
      },
      {
        treatmentNumber: 2,
        treatmentInformation: 'Claire',
        workerEmail: 'Cottisford',
        carNumber: 'ccottisford1@quantcast.com',
        date: 'Male',
      },
      {
        treatmentNumber: 3,
        treatmentInformation: 'Rayna',
        workerEmail: 'Czadla',
        carNumber: 'rczadla2@java.com',
        date: 'Female',
      },
      {
        treatmentNumber: 4,
        treatmentInformation: 'Claudelle',
        workerEmail: 'Ganley',
        carNumber: 'cganley3@eventbrite.com',
        date: 'Female',
      },
      {
        treatmentNumber: 5,
        treatmentInformation: 'Rudyard',
        workerEmail: 'Widdup',
        carNumber: 'rwiddup4@linkedin.com',
        date: 'Male',
      },
      {
        treatmentNumber: 6,
        treatmentInformation: 'Francesco',
        workerEmail: 'Walsham',
        carNumber: 'fwalsham5@pbs.org',
        date: 'Male',
      },
      {
        treatmentNumber: 7,
        treatmentInformation: 'Gratiana',
        workerEmail: 'Keyworth',
        carNumber: 'gkeyworth6@hud.gov',
        date: 'Female',
      },
      {
        treatmentNumber: 8,
        treatmentInformation: 'Perri',
        workerEmail: 'Playle',
        carNumber: 'pplayle7@youku.com',
        date: 'Female',
      },
      {
        treatmentNumber: 9,
        treatmentInformation: 'Averell',
        workerEmail: 'Kennewell',
        carNumber: 'akennewell8@bizjournals.com',
        date: 'Male',
      },
      {
        treatmentNumber: 10,
        treatmentInformation: 'Shane',
        workerEmail: 'Micah',
        carNumber: 'smicah9@ebay.co.uk',
        date: 'Male',
      },
      {
        treatmentNumber: 11,
        treatmentInformation: 'Fraser',
        workerEmail: 'Matfin',
        carNumber: 'fmatfina@columbia.edu',
        date: 'Male',
      },
      {
        treatmentNumber: 12,
        treatmentInformation: 'Alonso',
        workerEmail: 'Thalmann',
        carNumber: 'athalmannb@ow.ly',
        date: 'Male',
      },
      {
        treatmentNumber: 13,
        treatmentInformation: 'Kerri',
        workerEmail: 'Wallen',
        carNumber: 'kwallenc@sakura.ne.jp',
        date: 'Genderfluid',
      },
      {
        treatmentNumber: 14,
        treatmentInformation: 'Maxim',
        workerEmail: 'Shann',
        carNumber: 'mshannd@merriam-webster.com',
        date: 'Male',
      },
      {
        treatmentNumber: 15,
        treatmentInformation: 'Alana',
        workerEmail: 'Keeping',
        carNumber: 'akeepinge@mlb.com',
        date: 'Female',
      },
      {
        treatmentNumber: 16,
        treatmentInformation: 'Wolfgang',
        workerEmail: 'Beddin',
        carNumber: 'wbeddinf@networkadvertising.org',
        date: 'Male',
      },
      {
        treatmentNumber: 17,
        treatmentInformation: 'Beatrice',
        workerEmail: 'Taft',
        carNumber: 'btaftg@alexa.com',
        date: 'Genderqueer',
      },
      {
        treatmentNumber: 18,
        treatmentInformation: 'Steward',
        workerEmail: 'Athowe',
        carNumber: 'sathoweh@people.com.cn',
        date: 'Male',
      },
      {
        treatmentNumber: 19,
        treatmentInformation: 'Albina',
        workerEmail: 'Prin',
        carNumber: 'aprini@etsy.com',
        date: 'Female',
      },
      {
        treatmentNumber: 20,
        treatmentInformation: 'Allayne',
        workerEmail: 'Blunn',
        carNumber: 'ablunnj@nih.gov',
        date: 'Male',
      },
      {
        treatmentNumber: 21,
        treatmentInformation: 'Marion',
        workerEmail: 'Djuricic',
        carNumber: 'mdjuricick@samsung.com',
        date: 'Female',
      },
      {
        treatmentNumber: 22,
        treatmentInformation: 'Jamison',
        workerEmail: 'Chisman',
        carNumber: 'jchismanl@friendfeed.com',
        date: 'Male',
      },
      {
        treatmentNumber: 23,
        treatmentInformation: 'Gus',
        workerEmail: 'Prugel',
        carNumber: 'gprugelm@utexas.edu',
        date: 'Female',
      },
      {
        treatmentNumber: 24,
        treatmentInformation: 'Ellsworth',
        workerEmail: 'Simion',
        carNumber: 'esimionn@4shared.com',
        date: 'Male',
      },
      {
        treatmentNumber: 25,
        treatmentInformation: 'Ansel',
        workerEmail: 'Ganter',
        carNumber: 'agantero@is.gd',
        date: 'Male',
      },
      {
        treatmentNumber: 26,
        treatmentInformation: 'Fifine',
        workerEmail: 'Draayer',
        carNumber: 'fdraayerp@sciencedirect.com',
        date: 'Female',
      },
      {
        treatmentNumber: 27,
        treatmentInformation: 'Silvanus',
        workerEmail: 'Challicum',
        carNumber: 'schallicumq@washingtonpost.com',
        date: 'Male',
      },
      {
        treatmentNumber: 28,
        treatmentInformation: 'Patti',
        workerEmail: 'De Biaggi',
        carNumber: 'pdebiaggir@dmoz.org',
        date: 'Female',
      },
      {
        treatmentNumber: 29,
        treatmentInformation: 'Sasha',
        workerEmail: 'Shillabeer',
        carNumber: 'sshillabeers@mail.ru',
        date: 'Female',
      },
      {
        treatmentNumber: 30,
        treatmentInformation: 'Aubrey',
        workerEmail: 'Feare',
        carNumber: 'afearet@opensource.org',
        date: 'Female',
      },
      {
        treatmentNumber: 31,
        treatmentInformation: 'Davin',
        workerEmail: 'Scrauniage',
        carNumber: 'dscrauniageu@omniture.com',
        date: 'Male',
      },
      {
        treatmentNumber: 32,
        treatmentInformation: 'Emanuel',
        workerEmail: 'Spours',
        carNumber: 'espoursv@csmonitor.com',
        date: 'Male',
      },
      {
        treatmentNumber: 33,
        treatmentInformation: 'Daryl',
        workerEmail: 'Sewill',
        carNumber: 'dsewillw@behance.net',
        date: 'Female',
      },
      {
        treatmentNumber: 34,
        treatmentInformation: 'Emeline',
        workerEmail: 'Oiller',
        carNumber: 'eoillerx@purevolume.com',
        date: 'Female',
      },
      {
        treatmentNumber: 35,
        treatmentInformation: 'Stearn',
        workerEmail: 'Duke',
        carNumber: 'sdukey@plala.or.jp',
        date: 'Male',
      },
      {
        treatmentNumber: 36,
        treatmentInformation: 'Shayne',
        workerEmail: 'Veighey',
        carNumber: 'sveigheyz@blinklist.com',
        date: 'Male',
      },
      {
        treatmentNumber: 37,
        treatmentInformation: 'Gerrie',
        workerEmail: 'Filasov',
        carNumber: 'gfilasov10@cornell.edu',
        date: 'Male',
      },
      {
        treatmentNumber: 38,
        treatmentInformation: 'Araldo',
        workerEmail: 'Doubleday',
        carNumber: 'adoubleday11@wikimedia.org',
        date: 'Male',
      },
      {
        treatmentNumber: 39,
        treatmentInformation: 'Jilli',
        workerEmail: 'Oakly',
        carNumber: 'joakly12@sourceforge.net',
        date: 'Female',
      },
      {
        treatmentNumber: 40,
        treatmentInformation: 'Juieta',
        workerEmail: 'Greatbatch',
        carNumber: 'jgreatbatch13@wix.com',
        date: 'Female',
      },
      {
        treatmentNumber: 41,
        treatmentInformation: 'Doreen',
        workerEmail: 'Cail',
        carNumber: 'dcail14@goo.ne.jp',
        date: 'Female',
      },
      {
        treatmentNumber: 42,
        treatmentInformation: 'Brandie',
        workerEmail: 'Roberds',
        carNumber: 'broberds15@tinyurl.com',
        date: 'Female',
      },
      {
        treatmentNumber: 43,
        treatmentInformation: 'Rolf',
        workerEmail: 'MacAnespie',
        carNumber: 'rmacanespie16@github.com',
        date: 'Male',
      },
      {
        treatmentNumber: 44,
        treatmentInformation: 'Briano',
        workerEmail: 'Manser',
        carNumber: 'bmanser17@loc.gov',
        date: 'Male',
      },
      {
        treatmentNumber: 45,
        treatmentInformation: 'Des',
        workerEmail: 'Arnley',
        carNumber: 'darnley18@columbia.edu',
        date: 'Genderqueer',
      },
      {
        treatmentNumber: 46,
        treatmentInformation: 'Alyosha',
        workerEmail: 'Anderton',
        carNumber: 'aanderton19@go.com',
        date: 'Male',
      },
      {
        treatmentNumber: 47,
        treatmentInformation: 'Jeane',
        workerEmail: 'Escofier',
        carNumber: 'jescofier1a@tripod.com',
        date: 'Female',
      },
      {
        treatmentNumber: 48,
        treatmentInformation: 'Kenna',
        workerEmail: 'Doncaster',
        carNumber: 'kdoncaster1b@bravesites.com',
        date: 'Female',
      },
      {
        treatmentNumber: 49,
        treatmentInformation: 'Justus',
        workerEmail: 'Metts',
        carNumber: 'jmetts1c@netvibes.com',
        date: 'Male',
      },
      {
        treatmentNumber: 50,
        treatmentInformation: 'Emanuel',
        workerEmail: 'Buxcey',
        carNumber: 'ebuxcey1d@merriam-webster.com',
        date: 'Male',
      },
      {
        treatmentNumber: 51,
        treatmentInformation: 'Isa',
        workerEmail: 'Badger',
        carNumber: 'ibadger1e@dion.ne.jp',
        date: 'Male',
      },
      {
        treatmentNumber: 52,
        treatmentInformation: 'Mitch',
        workerEmail: 'Heading',
        carNumber: 'mheading1f@yelp.com',
        date: 'Male',
      },
      {
        treatmentNumber: 53,
        treatmentInformation: 'Ronica',
        workerEmail: 'McCabe',
        carNumber: 'rmccabe1g@ask.com',
        date: 'Female',
      },
      {
        treatmentNumber: 54,
        treatmentInformation: 'Brooke',
        workerEmail: 'Hourstan',
        carNumber: 'bhourstan1h@phoca.cz',
        date: 'Female',
      },
      {
        treatmentNumber: 55,
        treatmentInformation: 'Corene',
        workerEmail: 'Cardo',
        carNumber: 'ccardo1i@wix.com',
        date: 'Female',
      },
      {
        treatmentNumber: 56,
        treatmentInformation: 'Tamera',
        workerEmail: 'Carlisso',
        carNumber: 'tcarlisso1j@china.com.cn',
        date: 'Female',
      },
      {
        treatmentNumber: 57,
        treatmentInformation: 'Donella',
        workerEmail: "O'Feeny",
        carNumber: 'dofeeny1k@patch.com',
        date: 'Non-binary',
      },
      {
        treatmentNumber: 58,
        treatmentInformation: 'Georgie',
        workerEmail: 'Dobey',
        carNumber: 'gdobey1l@disqus.com',
        date: 'Female',
      },
      {
        treatmentNumber: 59,
        treatmentInformation: 'Emmit',
        workerEmail: 'Beals',
        carNumber: 'ebeals1m@businessinsider.com',
        date: 'Male',
      },
      {
        treatmentNumber: 60,
        treatmentInformation: 'Lesley',
        workerEmail: 'Midden',
        carNumber: 'lmidden1n@fotki.com',
        date: 'Female',
      },
      {
        treatmentNumber: 61,
        treatmentInformation: 'Georas',
        workerEmail: 'Whittet',
        carNumber: 'gwhittet1o@google.co.jp',
        date: 'Male',
      },
      {
        treatmentNumber: 62,
        treatmentInformation: 'Gibby',
        workerEmail: 'Lougheed',
        carNumber: 'glougheed1p@paginegialle.it',
        date: 'Male',
      },
      {
        treatmentNumber: 63,
        treatmentInformation: 'Calhoun',
        workerEmail: 'Liffey',
        carNumber: 'cliffey1q@wordpress.com',
        date: 'Male',
      },
      {
        treatmentNumber: 64,
        treatmentInformation: 'Max',
        workerEmail: "O'Kinedy",
        carNumber: 'mokinedy1r@facebook.com',
        date: 'Male',
      },
      {
        treatmentNumber: 65,
        treatmentInformation: 'Danyette',
        workerEmail: 'Skocroft',
        carNumber: 'dskocroft1s@google.ca',
        date: 'Female',
      },
      {
        treatmentNumber: 66,
        treatmentInformation: 'Corri',
        workerEmail: 'Wrightson',
        carNumber: 'cwrightson1t@qq.com',
        date: 'Female',
      },
      {
        treatmentNumber: 67,
        treatmentInformation: 'Ham',
        workerEmail: 'Saile',
        carNumber: 'hsaile1u@admin.ch',
        date: 'Male',
      },
      {
        treatmentNumber: 68,
        treatmentInformation: 'Antonius',
        workerEmail: 'Eckersley',
        carNumber: 'aeckersley1v@altervista.org',
        date: 'Male',
      },
      {
        treatmentNumber: 69,
        treatmentInformation: 'Dell',
        workerEmail: 'Baumadier',
        carNumber: 'dbaumadier1w@google.ca',
        date: 'Female',
      },
      {
        treatmentNumber: 70,
        treatmentInformation: 'Heindrick',
        workerEmail: 'Bernon',
        carNumber: 'hbernon1x@symantec.com',
        date: 'Genderfluid',
      },
      {
        treatmentNumber: 71,
        treatmentInformation: 'Agnella',
        workerEmail: 'Lief',
        carNumber: 'alief1y@ox.ac.uk',
        date: 'Female',
      },
      {
        treatmentNumber: 72,
        treatmentInformation: 'Lori',
        workerEmail: 'Simionescu',
        carNumber: 'lsimionescu1z@symantec.com',
        date: 'Female',
      },
      {
        treatmentNumber: 73,
        treatmentInformation: 'Shawnee',
        workerEmail: 'Matusiak',
        carNumber: 'smatusiak20@forbes.com',
        date: 'Female',
      },
      {
        treatmentNumber: 74,
        treatmentInformation: 'Seline',
        workerEmail: 'Oxnam',
        carNumber: 'soxnam21@globo.com',
        date: 'Female',
      },
      {
        treatmentNumber: 75,
        treatmentInformation: 'Horatio',
        workerEmail: 'Ciccarello',
        carNumber: 'hciccarello22@4shared.com',
        date: 'Male',
      },
      {
        treatmentNumber: 76,
        treatmentInformation: 'Armin',
        workerEmail: 'Steer',
        carNumber: 'asteer23@blinklist.com',
        date: 'Male',
      },
      {
        treatmentNumber: 77,
        treatmentInformation: 'Drusilla',
        workerEmail: 'Crohan',
        carNumber: 'dcrohan24@amazon.com',
        date: 'Female',
      },
      {
        treatmentNumber: 78,
        treatmentInformation: 'Iormina',
        workerEmail: 'Matteau',
        carNumber: 'imatteau25@xing.com',
        date: 'Female',
      },
      {
        treatmentNumber: 79,
        treatmentInformation: 'Rudy',
        workerEmail: 'Crinage',
        carNumber: 'rcrinage26@bravesites.com',
        date: 'Male',
      },
      {
        treatmentNumber: 80,
        treatmentInformation: 'Aldin',
        workerEmail: 'McAreavey',
        carNumber: 'amcareavey27@miitbeian.gov.cn',
        date: 'Male',
      },
      {
        treatmentNumber: 81,
        treatmentInformation: 'Nadine',
        workerEmail: 'Umpleby',
        carNumber: 'numpleby28@utexas.edu',
        date: 'Female',
      },
      {
        treatmentNumber: 82,
        treatmentInformation: 'Galen',
        workerEmail: 'Teresse',
        carNumber: 'gteresse29@meetup.com',
        date: 'Male',
      },
      {
        treatmentNumber: 83,
        treatmentInformation: 'Engelbert',
        workerEmail: 'Boyfield',
        carNumber: 'eboyfield2a@psu.edu',
        date: 'Male',
      },
      {
        treatmentNumber: 84,
        treatmentInformation: 'Kendell',
        workerEmail: 'Spargo',
        carNumber: 'kspargo2b@economist.com',
        date: 'Male',
      },
      {
        treatmentNumber: 85,
        treatmentInformation: 'Norina',
        workerEmail: 'Jeynes',
        carNumber: 'njeynes2c@xinhuanet.com',
        date: 'Female',
      },
      {
        treatmentNumber: 86,
        treatmentInformation: 'Shawn',
        workerEmail: 'MacIlurick',
        carNumber: 'smacilurick2d@seesaa.net',
        date: 'Female',
      },
      {
        treatmentNumber: 87,
        treatmentInformation: 'Hillary',
        workerEmail: 'Dondon',
        carNumber: 'hdondon2e@hubpages.com',
        date: 'Female',
      },
      {
        treatmentNumber: 88,
        treatmentInformation: 'Eustace',
        workerEmail: 'Nollet',
        carNumber: 'enollet2f@tinyurl.com',
        date: 'Male',
      },
      {
        treatmentNumber: 89,
        treatmentInformation: 'Rickert',
        workerEmail: 'Waddilove',
        carNumber: 'rwaddilove2g@gravatar.com',
        date: 'Bigender',
      },
      {
        treatmentNumber: 90,
        treatmentInformation: 'Cody',
        workerEmail: 'Edlestone',
        carNumber: 'cedlestone2h@webeden.co.uk',
        date: 'Female',
      },
      {
        treatmentNumber: 91,
        treatmentInformation: 'Lorry',
        workerEmail: "O'Callaghan",
        carNumber: 'locallaghan2i@unicef.org',
        date: 'Male',
      },
      {
        treatmentNumber: 92,
        treatmentInformation: 'Kingsly',
        workerEmail: 'Cheves',
        carNumber: 'kcheves2j@google.ca',
        date: 'Male',
      },
      {
        treatmentNumber: 93,
        treatmentInformation: 'Elvera',
        workerEmail: 'Anger',
        carNumber: 'eanger2k@yandex.ru',
        date: 'Female',
      },
      {
        treatmentNumber: 94,
        treatmentInformation: 'Denyse',
        workerEmail: 'Bickerdicke',
        carNumber: 'dbickerdicke2l@independent.co.uk',
        date: 'Female',
      },
      {
        treatmentNumber: 95,
        treatmentInformation: 'Alla',
        workerEmail: 'Taggett',
        carNumber: 'ataggett2m@google.co.uk',
        date: 'Female',
      },
      {
        treatmentNumber: 96,
        treatmentInformation: 'Ignace',
        workerEmail: 'Deesly',
        carNumber: 'ideesly2n@scientificamerican.com',
        date: 'Male',
      },
      {
        treatmentNumber: 97,
        treatmentInformation: 'Elyn',
        workerEmail: 'Gregorowicz',
        carNumber: 'egregorowicz2o@mac.com',
        date: 'Female',
      },
      {
        treatmentNumber: 98,
        treatmentInformation: 'Cullan',
        workerEmail: 'Farfull',
        carNumber: 'cfarfull2p@disqus.com',
        date: 'Male',
      },
      {
        treatmentNumber: 99,
        treatmentInformation: 'Yvette',
        workerEmail: 'Furney',
        carNumber: 'yfurney2q@mozilla.org',
        date: 'Female',
      },
      {
        treatmentNumber: 100,
        treatmentInformation: 'Sibelle',
        workerEmail: 'Peppard',
        carNumber: 'speppard2r@dropbox.com',
        date: 'Female',
      },
    ],
  };

  return (
    <div className='dataTable'>
      <MDBDataTable fixed hover={true} data={data} />
    </div>
  );
};
